/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 hall.gltf 
Author: ChristyHsu (https://sketchfab.com/ida61xq)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/auditorium-future-hall-baked-9be313cd17594198bd4cc477bcbfa16a
Title: Auditorium Future | Hall | Baked
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('newHall/hall.gltf')

  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[22.919, 60.086, 308.216]} rotation={[-Math.PI / 2, 0, 0]} scale={72.442}>
          <mesh geometry={nodes.roof_roof1_0.geometry} material={materials.roof1} />
          <mesh geometry={nodes.roof_roof2_0.geometry} material={materials.roof2} />
        </group>
        <group position={[-603.858, 127.098, 524.088]} scale={[19.719, 19.719, 19.72]}>
          <mesh geometry={nodes.pulpit_PULPIT1_0.geometry} material={materials.PULPIT1} />
          <mesh geometry={nodes.pulpit_PULPIT2_0.geometry} material={materials.PULPIT2} />
        </group>
        <group position={[1169.789, 10.47, 268.204]} rotation={[-Math.PI / 2, 0, 0]} scale={72.442}>
          <mesh geometry={nodes.seat_seat2001_0.geometry} material={materials['seat2.001']} />
          <mesh geometry={nodes.seat_seat1001_0.geometry} material={materials['seat1.001']} />
          <mesh geometry={nodes.seat_seat1001_0_1.geometry} material={materials['seat1.001']} />
          <mesh geometry={nodes.seat_seat1001_0_2.geometry} material={materials['seat1.001']} />
          <mesh geometry={nodes.seat_seat1001_0_3.geometry} material={materials['seat1.001']} />
          <mesh geometry={nodes.seat_seat1001_0_4.geometry} material={materials['seat1.001']} />
          <mesh geometry={nodes.seat_seat1001_0_5.geometry} material={materials['seat1.001']} />
          <mesh geometry={nodes.seat_seat1001_0_6.geometry} material={materials['seat1.001']} />
          <mesh geometry={nodes.seat_seat1001_0_7.geometry} material={materials['seat1.001']} />
        </group>
        <mesh geometry={nodes.screen_SCREEN_0.geometry} material={materials.SCREEN} position={[22.919, 55.27, 308.216]} rotation={[-Math.PI / 2, 0, 0]} scale={72.442} />
        <mesh geometry={nodes.floor_floor_0.geometry} material={materials.floor} position={[22.919, 11.081, 308.216]} rotation={[-Math.PI / 2, 0, 0]} scale={[76.422, 76.422, 72.442]} />
        <mesh geometry={nodes.house_house_0.geometry} material={materials.house} position={[22.919, 11.081, 69.409]} rotation={[-Math.PI / 2, 0, 0]} scale={72.442} />
        <mesh geometry={nodes.screen_structure_screen_structure_0.geometry} material={materials.screen_structure} position={[23.771, 51.86, 307.774]} rotation={[-Math.PI / 2, 0, 0]} scale={[72.148, 72.148, 67.827]} />
      </group>
    </group>
  )
}

useGLTF.preload('/hall.gltf')
